blog/urls.py
from django.urls import path
from .views import post_list_published, post_create, post_detail, post_update, post_delete, like,post_list_all, post_list_draft,PostList,PostRUD,comment,CommentRud,postCreate,CommentCreate
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "blog"

urlpatterns = [
    path('post/', PostList.as_view(), name='post_list'),
    path('post/create/', postCreate.as_view(), name='post_create'),
    path('post/<int:pk>', PostRUD.as_view(), name='post_rud'),
    path('post/comment/create/', CommentCreate.as_view(), name='comment_create'),
    path('post/comment/<int:pk>/', CommentRud.as_view(), name='comment_rud'), 
    


    path("",post_list_all, name="list_all"),
    path("published",post_list_published, name="list_published"),
    path("draft",post_list_draft, name="list_draft"),
    path("create/",post_create, name="create"),
    path("<str:slug>/",post_detail, name="detail"),
    path("<str:slug>/update/",post_update, name="update"),
    path("<str:slug>/delete/",post_delete, name="delete"),
    path("<str:slug>/like/",like, name="like"),
    path('<str:slug>/comment/', comment, name='comment'),
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin_panel"),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

def user_directory_path(instance, filename):
    return 'blog/{0}/{1}'.format(instance.author, filename)

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.name

class Post(models.Model):
    OPTIONS = (
        ('Draft', 'Draft'),
        ('Publish', 'Publish'),
    )
    

    id = models.AutoField(primary_key=True, editable=False, unique=True, null=False, blank=False)
    title = models.CharField(max_length=100)    
    content = models.TextField()
    image = models.ImageField(upload_to=user_directory_path, default='blog.jpg')
    category = models.ForeignKey(Category , on_delete=models.PROTECT, blank=True, null=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=100, default="Anonymous")
    status = models.CharField(max_length=10, choices=OPTIONS, default='Publish')
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
    
    
    def comment_count(self):
        return self.comment_set.all().count()
    
    def view_count(self):
        return self.postview_set.all().count()
    
    def like_count(self):
        return self.like_set.all().count()
    
    def comments(self):
        return self.comment_set.all()

class Comment(models.Model):
    id = models.AutoField(primary_key=True, editable=False, unique=True, null=False, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    slug = models.SlugField(blank=True, unique=True,default=uuid.uuid1)
    
    
    def __str__(self):
        return self.user.username
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username
    

blog/forms.py
from django import forms
from .models import Post, Comment, Category

class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False, empty_label="Select Category")
    class Meta:
        model = Post
        fields = (
            'title',
            'content',
            'image',
            'category',
            'status',
        )
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Post, Like, PostView, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from rest_framework import generics
from .serializers import PostSerializer, CommentSerializer, PostCreateSerializer, CommentCreateSerializer, PostUpdateSerializer, CommentUpdateSerializer
from django.http import JsonResponse




class PostList(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    
    # def get (self, request):
    #     qs = Post.objects.all()
    #     serializer = PostSerializer(qs, many=True)
    #     return JsonResponse(serializer.data, safe=False)


class postCreate(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return JsonResponse(serializer.data, status=201, headers=headers)  

class CommentCreate(generics.CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentCreateSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return JsonResponse(serializer.data, status=201, headers=headers)

class CommentRud(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentUpdateSerializer


class PostRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateSerializer

class like (generics.CreateAPIView):
    queryset = Like.objects.all()
    serializer_class = PostSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return JsonResponse(serializer.data, status=201, headers=headers)









def post_list_all(request):
    qs = Post.objects.all()
    context = {
        'object_list' : qs
    }
    return render (request, "blog/post_list.html", context )

def post_list_published(request):
    qs = Post.objects.filter(status='p')
    context = {
        'object_list' : qs
    }
    return render (request, "blog/post_list.html", context )

def post_list_draft(request):
    qs = Post.objects.filter(status='d')
    context = {
        'object_list' : qs
    }
    return render (request, "blog/post_list.html", context )

@login_required()
def post_create(request):
    # form = PostForm(request.POST or None, request.FILES or None)
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        # print(request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "Post created successfully!")
            return redirect("blog:list_all")
    context = {
        'form' : form
    }
    return render (request, "blog/post_create.html", context)

def post_detail(request, slug):
    # comment = Comment.objects.all( )
    # kim = request.user
    form = CommentForm()
    obj = get_object_or_404(Post, slug=slug)
    # like_qs = Like.objects.filter(user=request.user, post=obj)
    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=obj)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = obj
            comment.save()
            return redirect("blog:detail", slug=slug)
            # return redirect(request.path)
    context = {
        'object' : obj,
        "form" : form,
        # "like_qs" : like_qs,
        # 'kitap' : comment,
        # 'kim': kim
    }
    return render(request, "blog/post_detail.html", context)

@login_required()
def post_update(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if request.user.username != obj.author and not request.user.is_superuser:
        # return HttpResponse("You are not authorized!")
        messages.warning(request, "You are not a writer of this post !")
        return redirect("blog:list_all")
    if form.is_valid():
        form.save()
        messages.success(request, "Post updated !!")
        return redirect("blog:list_all")
    context = {
        "object" : obj,
        "form" : form
    }
    return render(request, "blog/post_update.html", context)

@login_required()
def post_delete(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    if request.user.username != obj.author and not request.user.is_superuser:
        # return HttpResponse("You are not authorized!")
        messages.warning(request, "You are not a writer of this post !")
        return redirect("blog:list_all")
    if request.method == "POST":
        obj.delete()
        messages.success(request, "Post deleted !!")
        return redirect("blog:list_all")    
    context = {
        "object" : obj
    }
    return render(request, "blog/post_delete.html", context)

@login_required()
def like(request, slug):
    if request.method == "POST":
        obj = get_object_or_404(Post, slug=slug)
        like_qs = Like.objects.filter(user=request.user, post=obj)
        if like_qs.exists():
            like_qs[0].delete()
        else:
            Like.objects.create(user=request.user, post=obj)
        return redirect("blog:detail", slug=slug)
    return redirect("blog:detail", slug=slug)

@login_required()
def comment(request, slug):
    obj = get_object_or_404(Comment, slug=slug)
    if request.user.id != obj.user.id and not request.user.is_superuser:
        # return HttpResponse("You are not authorized!")
        messages.warning(request, "You are not a writer of this post !")
        return redirect("blog:list_all")
    if request.method == "POST":
        obj.delete()
        messages.success(request, "Comment deleted !!")
        return redirect("blog:detail", slug=obj.post.slug)
    return redirect("blog:detail", slug=slug)

blog/templates/blog/post_create.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Blog Post</h3>
    <hr />
    <form method="POST" enctype="multipart/form-data">   
      {% csrf_token %} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-outline-info">Post</button>
    </form>
  </div>
</div>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row mt-5">
  <div class="col-md-6">
    <div class="card card-body">
      <div class="card-body">
        <h5 class="card-title">Are you sure you want to delete "{{object}}"</h5>
        <form action=" " method="POST">
          {% csrf_token %}
          <a class="btn btn-warning" href="{% url 'blog:list_all' %}">Cancel</a>
          <button class="btn btn-danger" type="submit">Confirm</button>
        </form>
      </div>      
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container card" style="width: 40rem;">
        <img src="{{ object.image.url }}" class="card-img-top" alt="post_image">
        <div class="card-body">
            <h2 class="card-title">{{ object.title }}</h2>
            <hr>

            <div>
                <span><i class="far fa-comment-alt ml-2"></i></i> {{ object.comment_count }}</span>
                <span><i class="fas fa-eye ml-2"></i> {{ object.view_count }}</span>
                <span><i class="fa-solid fa-heart ml-2"></i> {{ object.like_count }}</span>
                <span class="float-right"> <small>Posted {{ object.publish_date|timesince }} ago.</small> </span>
            </div>
            <hr>

            <p class="card-text">{{ object.content }}.</p>
            <hr>

            <div>
            <h4>Enjoy this post? Give it a LIKE!!</h4>
            </div>

            <div>
            <form action="{% url 'blog:like' object.slug %}" method="POST">

                {% csrf_token %}
                <input type="hidden" name="post">
                <input type="hidden" name="user">


                <button type="submit"><i class="fa-solid fa-heart fa-lg"></i></button>
                {{object.like_count }}
            </form>
            <hr>
            {% if user.is_authenticated %}
            <h4>Leave a comment below</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-secondary btn-sm mt-1 mb-1">SEND</button>
            </form>
            <hr>
            {% endif %}
            <h4>Comments</h4>
            {% for comment in object.comments %}
            <div>
                
                <form action="{% url 'blog:comment' comment.slug %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="post">
                    <input type="hidden" name="user">
                    <p>
                        <small><b>Comment by {{comment.user}}</b></small> - <small>{{ comment.time_stamp|timesince }} ago.
                        </small>
                    </p>
                    <p>
                        {{ comment.content }} 
                        {% if user.id == comment.user.id or user.is_superuser %}
                        <button type="submit"><i class="fa-solid fa-trash"></i></button>
                        {% endif %}
    
                    </p>
                    
                   
                    </form>
            </div>
            <hr>
            {% endfor %}
        
        </div>

        </div>

        <div class="m-3">
        {% if user.username == object.author or user.is_superuser      %}
        <a href="{% url 'blog:update' object.slug %}" class="btn btn-info">Edit</a>
        <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </div>
   

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}


{% block content %}
<h1 style="text-align: center;">Cem Blog</h1>
<div class="row mt-5" >
    {% for obj in object_list %}
    <div class="col-4">
        <a href="{% url 'blog:detail' obj.slug %}" style="text-decoration:none;   color: inherit;      ">

        <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem; min-height:min-content; ">
            <img src="{{ obj.image.url }}" class="card-img-top" alt="post_image" style="width:15rem; height: 11rem; align-self:center;">
            <hr>
            <div class="card-body">
                <h5 class="card-title">{{obj.title}}</h5>
                <p class="card-text">{{obj.content|truncatechars:20}}</p>

                <p>
                <p class="card-text"><small>
                        <!-- Posted {{ obj.publish_date|timesince }} ago. -->
                        Created {{ obj.publish_date }}
                    </small>
                </p>
                <p class="card-text">
                    <small style="text-transform: capitalize; " >
                    Created by {{ obj.author }}

                    </small>
                </p>
                
                <span><i class="far fa-comment-alt ml-2"></i>{{ obj.comment_count }}</span>
                <span><i class="fas fa-eye ml-2"></i>{{ obj.view_count }}</span>
                <span><i class="fa-solid fa-heart ml-2"></i>{{ obj.like_count }}</span>

                </p>
            </div>
        </div>
        </a>
    </div>

    {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Update Post</h3>
    <hr />
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-outline-info">Update</button>
    </form>
  </div>
</div>

{% endblock content %}